# Generated by Django 3.1.5 on 2021-05-06 01:50

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('direct', '0002_auto_20210422_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='国'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(1, '女性'), (2, '男性')], max_length=2, verbose_name='性別'),
        ),
    ]
